[graph]
all-features = true
exclude = ["generate", "assembler"]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
