[package]
name = "generate"
version = "0.1.0"
edition.workspace = true
publish = false

[package.metadata.release]
release = false

[[bin]]
name = "generate"
path = "main.rs"
test = false
bench = false
